site_name: Shopify Order Automation
theme:
  name: readthedocs
  user_color_mode_toggle : true
  logo: assets/logo.jpg
  locale: en
plugins:
  - swagger-ui-tag
  - search
  - mermaid2
nav:
  - Accueil: index.md
  - Guide:
      - Getting Started: getting-started.md
  - API Docs:
      - API Authentication: api-docs/api.md
      - Swagger API Endpoints: api-docs/api-endpoints.md
  - Mainfeatures Docs:
      - mainfeatures-docs: mainfeatures-docs/features.md
  - Technicalarchitecture Docs:
      - Architecture: technicalarchitecture-docs/architecture.md
      - Roadmap: technicalarchitecture-docs/roadmap.md
  - Faq and Glossary:
      - faq_and_glossary: faq_and_glossary/faq.md
  - About:
      - About: about/about.md

     